name: CI
on: [push, pull_request]

jobs:

  package-haxelib:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - uses: actions/upload-artifact@v3
        with:
          name: starling-haxelib
          path: |
            ./
            !lib/
            !samples/
            !scripts/
            !tests/
            !haxe-*-*/
            !neko-*-*/
            !.git/
            !webpack.*
            !package.json
          if-no-files-found: error

  docs:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.2.5

      - name: Set HAXEPATH
        run: |
          echo "HAXEPATH=$HAXE_STD_PATH/.." >> $GITHUB_ENV

      - name: Install Haxe dependencies
        run: |
          haxelib install lime --quiet
          haxelib install openfl --quiet
          haxelib install dox --quiet
          haxelib dev starling $GITHUB_WORKSPACE

      - name: Build docs
        working-directory: scripts
        run: |
          haxe docs.hxml

      - uses: actions/upload-artifact@v3
        with:
          name: starling-docs
          path: docs
          if-no-files-found: error

  samples:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.0.5

      - uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Set HAXEPATH
        run: |
          echo "HAXEPATH=$HAXE_STD_PATH/.." >> $GITHUB_ENV

      - name: Install Haxe dependencies
        run: |
          haxelib install lime --quiet
          haxelib install openfl --quiet
          haxelib dev starling $GITHUB_WORKSPACE

      - name: Build samples/demo
        working-directory: samples/demo
        run: |
          haxelib run lime build html5
          haxelib run lime build neko
          haxelib run lime build hl
          haxelib run lime build flash

      - name: Build samples/particle_demo
        working-directory: samples/particle_demo
        run: |
          haxelib run lime build html5
          haxelib run lime build neko
          haxelib run lime build hl
          haxelib run lime build flash

      - name: Build samples/demo_npm/as3
        working-directory: samples/demo_npm/as3
        run: |
          npm install
          npm run build

      - name: Build samples/demo_npm/es5
        working-directory: samples/demo_npm/es5
        run: |
          npm install
          npm run build

      - name: Build samples/demo_npm/es6
        working-directory: samples/demo_npm/es6
        run: |
          npm install
          npm run build

      - name: Build samples/demo_npm/haxe
        working-directory: samples/demo_npm/haxe
        run: |
          npm install
          npm run build

      - name: Build samples/demo_npm/typescript
        working-directory: samples/demo_npm/typescript
        run: |
          npm install
          npm run build

  build-npm:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install Dependencies
        run: |
          npm install

      - name: Build Library
        run: |
          npm run build

      - name: Package Library for npm
        run: |
          npm pack

      - uses: actions/upload-artifact@v3
        with:
          name: starling-framework-npm
          path: starling-framework-*.tgz
          if-no-files-found: error

      - name: Build docs
        run: |
          npm run build-docs